### ISSUE TITLE
Android soft bridge not working

### ISSUE THREAD

**Issue by huk13** [Zefau/ioBroker.nuki-extended#66] opened 2020-05-01 10:54 UTC
I use the latest version of the Nuki Lock 2 and of the Android software bridge on a Samsung S3. 
The lock states are not correctly updated. If an action is started the warning: (21913) Neither Bridge API or Web API initialized! is displayed but nothing is transmitted. Here is a log showing the start of the adapter und the initiation of the action:
```
2020-05-02 10:40:30.813 - info: host.raspi-3 stopInstance system.adapter.nuki-extended.0 (force=false, process=true)
2020-05-02 10:40:30.834 - info: host.raspi-3 stopInstance system.adapter.nuki-extended.0 send kill signal
2020-05-02 10:40:30.835 - info: nuki-extended.0 (13146) Got terminate signal TERMINATE_YOURSELF
2020-05-02 10:40:30.838 - info: nuki-extended.0 (13146) Adapter stopped und unloaded.
2020-05-02 10:40:30.840 - info: nuki-extended.0 (13146) terminating
2020-05-02 10:40:30.842 - info: nuki-extended.0 (13146) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
2020-05-02 10:40:31.378 - info: host.raspi-3 instance system.adapter.nuki-extended.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
2020-05-02 10:40:33.910 - info: host.raspi-3 instance system.adapter.nuki-extended.0 started with pid 14128
2020-05-02 10:40:35.222 - debug: nuki-extended.0 (14128) Redis Objects: Use Redis connection: 127.0.0.1:9001
2020-05-02 10:40:35.267 - debug: nuki-extended.0 (14128) Objects client ready ... initialize now
2020-05-02 10:40:35.270 - debug: nuki-extended.0 (14128) Objects create System PubSub Client
2020-05-02 10:40:35.272 - debug: nuki-extended.0 (14128) Objects create User PubSub Client
2020-05-02 10:40:35.273 - debug: nuki-extended.0 (14128) Objects client initialize lua scripts
2020-05-02 10:40:35.294 - debug: nuki-extended.0 (14128) Objects connected to redis: 127.0.0.1:9001
2020-05-02 10:40:35.301 - debug: nuki-extended.0 (14128) objectDB connected
2020-05-02 10:40:35.304 - debug: nuki-extended.0 (14128) Redis States: Use Redis connection: 127.0.0.1:6379
2020-05-02 10:40:35.309 - debug: nuki-extended.0 (14128) States create User PubSub Client
2020-05-02 10:40:35.312 - debug: nuki-extended.0 (14128) States create System PubSub Client
2020-05-02 10:40:35.320 - debug: nuki-extended.0 (14128) States connected to redis: 127.0.0.1:6379
2020-05-02 10:40:35.321 - debug: nuki-extended.0 (14128) statesDB connected
2020-05-02 10:40:36.694 - info: nuki-extended.0 (14128) starting. Version 2.2.5 in /opt/iobroker/node_modules/iobroker.nuki-extended, node: v12.16.2, js-controller: 3.0.20
2020-05-02 10:40:37.753 - debug: nuki-extended.0 (14128) getBridgeApi() [forcePlainToken: true]: [{"nukiId":496539692,"name":"Haustür","lastKnownState":{"state":3,"stateName":"unlocked","batteryCritical":false,"timestamp":"2020-05-02T10:04:18+02:00"},"nuki":{"_events":{},"_eventsCount":0,"_maxListeners":100,"connection":{"ip":"192.168.178.59","port":8080,"token":"xxxxxx","type":2,"forcePlainToken":true,"delayBetweenRequests":250,"delayer":{"isFulfilled":false,"isRejected":false}},"nukiId":496539692,"deviceType":0}}]
2020-05-02 10:40:37.758 - debug: nuki-extended.0 (14128) Error updating device due to missing data ({"nukiId":496539692,"name":"Haustür","nuki":{"_events":{},"_eventsCount":0,"_maxListeners":100,"connection":{"ip":"192.168.178.59","port":8080,"token":"xxxxxx","type":2,"forcePlainToken":true,"delayBetweenRequests":250,"delayer":{"isFulfilled":false,"isRejected":false}},"nukiId":496539692,"deviceType":0},"bridge":"1856742785","state":{"state":3,"stateName":"unlocked","batteryCritical":false,"timestamp":"2020-05-02T10:04:18+02:00"},"nukiHexId":"1d98982c"}).
2020-05-02 10:40:38.412 - debug: nuki-extended.0 (14128) Retrieved current callbacks from Nuki Bridge with name Door.
2020-05-02 10:40:38.418 - debug: nuki-extended.0 (14128) Callback (with URL http://192.168.178.78:51989/nuki-api-bridge) already attached to Nuki Bridge with name Door.
2020-05-02 10:40:38.463 - info: nuki-extended.0 (14128) Polling Nuki Web API with a frequency of 5s.
2020-05-02 10:40:38.465 - info: nuki-extended.0 (14128) Listening for Nuki events on port 51989.
2020-05-02 10:40:38.625 - debug: nuki-extended.0 (14128) getWebApi(): [{"smartlockId":496539692,"accountId":783926648,"type":0,"authId":3431657,"name":"Haustür","favorite":false,"config":{"name":"Haustür","latitude":51.698242,"longitude":10.003996,"autoUnlatch":true,"pairingEnabled":true,"buttonEnabled":true,"ledEnabled":false,"ledBrightness":1,"timezoneOffset":0,"daylightSavingMode":0,"fobPaired":false,"fobAction1":4,"fobAction2":1,"fobAction3":2,"singleLock":false,"advertisingMode":0,"keypadPaired":false,"homekitState":1,"timezoneId":37},"advancedConfig":{"totalDegrees":23773,"singleLockedPositionOffsetDegrees":-90,"unlockedToLockedTransitionOffsetDegrees":0,"unlockedPositionOffsetDegrees":90,"lockedPositionOffsetDegrees":-90,"detachedCylinder":false,"batteryType":0,"lngTimeout":15,"singleButtonPressAction":1,"doubleButtonPressAction":5,"automaticBatteryTypeDetection":true,"unlatchDuration":1,"autoLockTimeout":0},"state":{"mode":2,"state":3,"trigger":0,"lastAction":1,"batteryCritical":false,"doorState":2,"ringToOpenTimer":0,"nightMode":false},"firmwareVersion":132614,"hardwareVersion":2817,"serverState":0,"adminPinState":0,"virtualDevice":false,"creationDate":"2020-05-01T09:45:24.259Z","updateDate":"2020-05-02T08:04:18.316Z"}]
2020-05-02 10:40:38.631 - debug: nuki-extended.0 (14128) Updating device smartlocks.haustür with payload: {"smartlockId":496539692,"accountId":783926648,"authId":3431657,"name":"Haustür","favorite":false,"config":{"name":"Haustür","latitude":51.698242,"longitude":10.003996,"autoUnlatch":true,"pairingEnabled":true,"buttonEnabled":true,"ledEnabled":false,"ledBrightness":1,"timezoneOffset":0,"daylightSavingMode":0,"fobPaired":false,"fobAction1":4,"fobAction2":1,"fobAction3":2,"singleLock":false,"advertisingMode":0,"keypadPaired":false,"homekitState":1,"timezoneId":37},"advancedConfig":{"totalDegrees":23773,"singleLockedPositionOffsetDegrees":-90,"unlockedToLockedTransitionOffsetDegrees":0,"unlockedPositionOffsetDegrees":90,"lockedPositionOffsetDegrees":-90,"detachedCylinder":false,"batteryType":0,"lngTimeout":15,"singleButtonPressAction":1,"doubleButtonPressAction":5,"automaticBatteryTypeDetection":true,"unlatchDuration":1,"autoLockTimeout":0},"state":{"trigger":0,"lastAction":1,"batteryCritical":false,"doorState":2,"ringToOpenTimer":0,"nightMode":false,"timestamp":"2020-05-02T08:40:38+00:00","closed":2},"firmwareVersion":132614,"hardwareVersion":2817,"serverState":0,"adminPinState":0,"virtualDevice":false,"creationDate":"2020-05-01T09:45:24.259Z","updateDate":"2020-05-02T08:04:18.316Z","nukiHexId":"1d98982c","deviceType":0,"nukiId":496539692}
2020-05-02 10:40:43.542 - debug: nuki-extended.0 (14128) getWebApi(): [{"smartlockId":496539692,"accountId":783926648,"type":0,"authId":3431657,"name":"Haustür","favorite":false,"config":{"name":"Haustür","latitude":51.698242,"longitude":10.003996,"autoUnlatch":true,"pairingEnabled":true,"buttonEnabled":true,"ledEnabled":false,"ledBrightness":1,"timezoneOffset":0,"daylightSavingMode":0,"fobPaired":false,"fobAction1":4,"fobAction2":1,"fobAction3":2,"singleLock":false,"advertisingMode":0,"keypadPaired":false,"homekitState":1,"timezoneId":37},"advancedConfig":{"totalDegrees":23773,"singleLockedPositionOffsetDegrees":-90,"unlockedToLockedTransitionOffsetDegrees":0,"unlockedPositionOffsetDegrees":90,"lockedPositionOffsetDegrees":-90,"detachedCylinder":false,"batteryType":0,"lngTimeout":15,"singleButtonPressAction":1,"doubleButtonPressAction":5,"automaticBatteryTypeDetection":true,"unlatchDuration":1,"autoLockTimeout":0},"state":{"mode":2,"state":3,"trigger":0,"lastAction":1,"batteryCritical":false,"doorState":2,"ringToOpenTimer":0,"nightMode":false},"firmwareVersion":132614,"hardwareVersion":2817,"serverState":0,"adminPinState":0,"virtualDevice":false,"creationDate":"2020-05-01T09:45:24.259Z","updateDate":"2020-05-02T08:04:18.316Z"}]
2020-05-02 10:40:43.544 - debug: nuki-extended.0 (14128) Updating device smartlocks.haustür with payload: {"smartlockId":496539692,"accountId":783926648,"authId":3431657,"name":"Haustür","favorite":false,"config":{"name":"Haustür","latitude":51.698242,"longitude":10.003996,"autoUnlatch":true,"pairingEnabled":true,"buttonEnabled":true,"ledEnabled":false,"ledBrightness":1,"timezoneOffset":0,"daylightSavingMode":0,"fobPaired":false,"fobAction1":4,"fobAction2":1,"fobAction3":2,"singleLock":false,"advertisingMode":0,"keypadPaired":false,"homekitState":1,"timezoneId":37},"advancedConfig":{"totalDegrees":23773,"singleLockedPositionOffsetDegrees":-90,"unlockedToLockedTransitionOffsetDegrees":0,"unlockedPositionOffsetDegrees":90,"lockedPositionOffsetDegrees":-90,"detachedCylinder":false,"batteryType":0,"lngTimeout":15,"singleButtonPressAction":1,"doubleButtonPressAction":5,"automaticBatteryTypeDetection":true,"unlatchDuration":1,"autoLockTimeout":0},"state":{"trigger":0,"lastAction":1,"batteryCritical":false,"doorState":2,"ringToOpenTimer":0,"nightMode":false,"timestamp":"2020-05-02T08:40:43+00:00","closed":2},"firmwareVersion":132614,"hardwareVersion":2817,"serverState":0,"adminPinState":0,"virtualDevice":false,"creationDate":"2020-05-01T09:45:24.259Z","updateDate":"2020-05-02T08:04:18.316Z","nukiHexId":"1d98982c","deviceType":0,"nukiId":496539692}
2020-05-02 10:40:43.679 - info: javascript.0 (1401) script.js.Sensoren.Klima_Temperatur_Wohnzimmer: Temperatur Wohnzimmer: 20.2
2020-05-02 10:40:48.554 - debug: nuki-extended.0 (14128) getWebApi(): [{"smartlockId":496539692,"accountId":783926648,"type":0,"authId":3431657,"name":"Haustür","favorite":false,"config":{"name":"Haustür","latitude":51.698242,"longitude":10.003996,"autoUnlatch":true,"pairingEnabled":true,"buttonEnabled":true,"ledEnabled":false,"ledBrightness":1,"timezoneOffset":0,"daylightSavingMode":0,"fobPaired":false,"fobAction1":4,"fobAction2":1,"fobAction3":2,"singleLock":false,"advertisingMode":0,"keypadPaired":false,"homekitState":1,"timezoneId":37},"advancedConfig":{"totalDegrees":23773,"singleLockedPositionOffsetDegrees":-90,"unlockedToLockedTransitionOffsetDegrees":0,"unlockedPositionOffsetDegrees":90,"lockedPositionOffsetDegrees":-90,"detachedCylinder":false,"batteryType":0,"lngTimeout":15,"singleButtonPressAction":1,"doubleButtonPressAction":5,"automaticBatteryTypeDetection":true,"unlatchDuration":1,"autoLockTimeout":0},"state":{"mode":2,"state":3,"trigger":0,"lastAction":1,"batteryCritical":false,"doorState":2,"ringToOpenTimer":0,"nightMode":false},"firmwareVersion":132614,"hardwareVersion":2817,"serverState":0,"adminPinState":0,"virtualDevice":false,"creationDate":"2020-05-01T09:45:24.259Z","updateDate":"2020-05-02T08:04:18.316Z"}]
2020-05-02 10:40:48.556 - debug: nuki-extended.0 (14128) Updating device smartlocks.haustür with payload: {"smartlockId":496539692,"accountId":783926648,"authId":3431657,"name":"Haustür","favorite":false,"config":{"name":"Haustür","latitude":51.698242,"longitude":10.003996,"autoUnlatch":true,"pairingEnabled":true,"buttonEnabled":true,"ledEnabled":false,"ledBrightness":1,"timezoneOffset":0,"daylightSavingMode":0,"fobPaired":false,"fobAction1":4,"fobAction2":1,"fobAction3":2,"singleLock":false,"advertisingMode":0,"keypadPaired":false,"homekitState":1,"timezoneId":37},"advancedConfig":{"totalDegrees":23773,"singleLockedPositionOffsetDegrees":-90,"unlockedToLockedTransitionOffsetDegrees":0,"unlockedPositionOffsetDegrees":90,"lockedPositionOffsetDegrees":-90,"detachedCylinder":false,"batteryType":0,"lngTimeout":15,"singleButtonPressAction":1,"doubleButtonPressAction":5,"automaticBatteryTypeDetection":true,"unlatchDuration":1,"autoLockTimeout":0},"state":{"trigger":0,"lastAction":1,"batteryCritical":false,"doorState":2,"ringToOpenTimer":0,"nightMode":false,"timestamp":"2020-05-02T08:40:48+00:00","closed":2},"firmwareVersion":132614,"hardwareVersion":2817,"serverState":0,"adminPinState":0,"virtualDevice":false,"creationDate":"2020-05-01T09:45:24.259Z","updateDate":"2020-05-02T08:04:18.316Z","nukiHexId":"1d98982c","deviceType":0,"nukiId":496539692}
2020-05-02 10:40:49.683 - debug: nuki-extended.0 (14128) State of nuki-extended.0.smartlocks.haustür._ACTION has changed {"val":2,"ack":false,"ts":1588408849676,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":1588408849676}.
2020-05-02 10:40:49.686 - info: nuki-extended.0 (14128) Trigger action -LOCK- on Nuki Smartlock Haustür (via Bridge API).
2020-05-02 10:40:49.688 - warn: nuki-extended.0 (14128) Neither Bridge API or Web API initialized!
2020-05-02 10:40:49.689 - debug: nuki-extended.0 (14128) DEVICE:{"id":496539692,"hex":"1d98982c","smartlockId":496539692,"name":"Haustür","type":"Smartlock","path":"smartlocks.haustür","bridge":null,"config":{"name":"Haustür","latitude":51.698242,"longitude":10.003996,"autoUnlatch":true,"pairingEnabled":true,"buttonEnabled":true,"ledEnabled":false,"ledBrightness":1,"timezoneOffset":0,"daylightSavingMode":0,"fobPaired":false,"fobAction1":4,"fobAction2":1,"fobAction3":2,"singleLock":false,"advertisingMode":0,"keypadPaired":false,"homekitState":1,"timezoneId":37},"advancedConfig":{"totalDegrees":23773,"singleLockedPositionOffsetDegrees":-90,"unlockedToLockedTransitionOffsetDegrees":0,"unlockedPositionOffsetDegrees":90,"lockedPositionOffsetDegrees":-90,"detachedCylinder":false,"batteryType":0,"lngTimeout":15,"singleButtonPressAction":1,"doubleButtonPressAction":5,"automaticBatteryTypeDetection":true,"unlatchDuration":1,"autoLockTimeout":0}}
2020-05-02 10:40:49.689 - debug: nuki-extended.0 (14128) Bridge API:undefined
2020-05-02 10:40:49.690 - debug: nuki-extended.0 (14128) Web API: {"token":"xxxapi_tokenxxx","url":"https://api.nuki.io"}
2020-05-02 10:40:49.699 - debug: nuki-extended.0 (14128) State of nuki-extended.0.smartlocks.haustür._ACTION has changed {"val":0,"ack":true,"ts":1588408849684,"q":0,"from":"system.adapter.nuki-extended.0","user":"system.user.admin","lc":1588408849684}.
2020-05-02 10:40:53.559 - debug: nuki-extended.0 (14128) getWebApi(): [{"smartlockId":496539692,"accountId":783926648,"type":0,"authId":3431657,"name":"Haustür","favorite":false,"config":{"name":"Haustür","latitude":51.698242,"longitude":10.003996,"autoUnlatch":true,"pairingEnabled":true,"buttonEnabled":true,"ledEnabled":false,"ledBrightness":1,"timezoneOffset":0,"daylightSavingMode":0,"fobPaired":false,"fobAction1":4,"fobAction2":1,"fobAction3":2,"singleLock":false,"advertisingMode":0,"keypadPaired":false,"homekitState":1,"timezoneId":37},"advancedConfig":{"totalDegrees":23773,"singleLockedPositionOffsetDegrees":-90,"unlockedToLockedTransitionOffsetDegrees":0,"unlockedPositionOffsetDegrees":90,"lockedPositionOffsetDegrees":-90,"detachedCylinder":false,"batteryType":0,"lngTimeout":15,"singleButtonPressAction":1,"doubleButtonPressAction":5,"automaticBatteryTypeDetection":true,"unlatchDuration":1,"autoLockTimeout":0},"state":{"mode":2,"state":3,"trigger":0,"lastAction":1,"batteryCritical":false,"doorState":2,"ringToOpenTimer":0,"nightMode":false},"firmwareVersion":132614,"hardwareVersion":2817,"serverState":0,"adminPinState":0,"virtualDevice":false,"creationDate":"2020-05-01T09:45:24.259Z","updateDate":"2020-05-02T08:04:18.316Z"}]
2020-05-02 10:40:53.561 - debug: nuki-extended.0 (14128) Updating device smartlocks.haustür with payload: {"smartlockId":496539692,"accountId":783926648,"authId":3431657,"name":"Haustür","favorite":false,"config":{"name":"Haustür","latitude":51.698242,"longitude":10.003996,"autoUnlatch":true,"pairingEnabled":true,"buttonEnabled":true,"ledEnabled":false,"ledBrightness":1,"timezoneOffset":0,"daylightSavingMode":0,"fobPaired":false,"fobAction1":4,"fobAction2":1,"fobAction3":2,"singleLock":false,"advertisingMode":0,"keypadPaired":false,"homekitState":1,"timezoneId":37},"advancedConfig":{"totalDegrees":23773,"singleLockedPositionOffsetDegrees":-90,"unlockedToLockedTransitionOffsetDegrees":0,"unlockedPositionOffsetDegrees":90,"lockedPositionOffsetDegrees":-90,"detachedCylinder":false,"batteryType":0,"lngTimeout":15,"singleButtonPressAction":1,"doubleButtonPressAction":5,"automaticBatteryTypeDetection":true,"unlatchDuration":1,"autoLockTimeout":0},"state":{"trigger":0,"lastAction":1,"batteryCritical":false,"doorState":2,"ringToOpenTimer":0,"nightMode":false,"timestamp":"2020-05-02T08:40:53+00:00","closed":2},"firmwareVersion":132614,"hardwareVersion":2817,"serverState":0,"adminPinState":0,"virtualDevice":false,"creationDate":"2020-05-01T09:45:24.259Z","updateDate":"2020-05-02T08:04:18.316Z","nukiHexId":"1d98982c","deviceType":0,"nukiId":496539692}
2020-05-02 10:40:58.558 - debug: nuki-extended.0 (14128) getWebApi(): [{"smartlockId":496539692,"accountId":783926648,"type":0,"authId":3431657,"name":"Haustür","favorite":false,"config":{"name":"Haustür","latitude":51.698242,"longitude":10.003996,"autoUnlatch":true,"pairingEnabled":true,"buttonEnabled":true,"ledEnabled":false,"ledBrightness":1,"timezoneOffset":0,"daylightSavingMode":0,"fobPaired":false,"fobAction1":4,"fobAction2":1,"fobAction3":2,"singleLock":false,"advertisingMode":0,"keypadPaired":false,"homekitState":1,"timezoneId":37},"advancedConfig":{"totalDegrees":23773,"singleLockedPositionOffsetDegrees":-90,"unlockedToLockedTransitionOffsetDegrees":0,"unlockedPositionOffsetDegrees":90,"lockedPositionOffsetDegrees":-90,"detachedCylinder":false,"batteryType":0,"lngTimeout":15,"singleButtonPressAction":1,"doubleButtonPressAction":5,"automaticBatteryTypeDetection":true,"unlatchDuration":1,"autoLockTimeout":0},"state":{"mode":2,"state":3,"trigger":0,"lastAction":1,"batteryCritical":false,"doorState":2,"ringToOpenTimer":0,"nightMode":false},"firmwareVersion":132614,"hardwareVersion":2817,"serverState":0,"adminPinState":0,"virtualDevice":false,"creationDate":"2020-05-01T09:45:24.259Z","updateDate":"2020-05-02T08:04:18.316Z"}]
```

**Comment by Zefau** [comment] 2020-05-03 19:04
Did you solve it or does the bug still persist? Are you using the correct token on the Bridge? it must be two different tokens.

**Comment by huk13** [comment] 2020-05-03 20:01
The  bug still persists. I use two different tokens. The one (6 digits) that I find in the bridge app for the configuration of the Nuki bridge and the one (very long) that is created on the web page for the configuration of web Nuki.

**Comment by Zefau** [comment] 2020-07-07 20:42
Sorry for the delay. Could you try 2.2.6 if that fixes the issue? Thanks, Zefau

**Comment by huk13** [comment] 2020-07-08 10:15
I installed 2,.2.6. Actions are working now, Thanks.
However, nuki door states are not changing accordingly. lastDataUpdate refreshes every 15 sec as set in the configuration. Everything else is dead,
Thanks and regards

**Comment by Zefau** [comment] 2020-07-08 20:06
Could you try both via smartphone app and via Nuki Web (https://web.nuki.io) ? Is both not working for you?

I'm facing the same issue, but apparently it looks like the smartphone app is not syncing with Nuki Web. Nuki Web though is correctly syncing with ioBroker.

**Comment by Zefau** [comment] 2020-07-08 20:08
https://github.com/Zefau/ioBroker.nuki-extended/issues/59

**Comment by huk13** [comment] 2020-07-08 20:23
Hello,

I compared the activity log in ioBroker and in the Nuki Web. They are the same but stopped this morning with the last entry at 11:50. The Nuki app shows the full activity log, last entry Lock at 22:00. This confirms your conclusion.

Regards HUK

**Comment by Zefau** [comment] 2020-07-09 16:58
I'm closing this issue, since the problem is solved. I reopened https://github.com/Zefau/ioBroker.nuki-extended/issues/59. I will keep an eye on this, but for me it seems to be an "foreign issue" with the smartphone app.

**Closed** 2020-07-09 16:58 UTC
Labels: bug, verify-fix
